name: manual trigger

on:
 workflow dispatch
 inputs:
 name:
 desciption: who to greet
  
  job:
      build:
      run-on: ubuntu-latest
      
    steps:
    -name: greeting
     run: echo "hello ${{github.event.inputs.name}}"
    
  
   
